name: cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Build
      run: |
        ./autogen.sh
        ./configure
        make

    - name: Run cppcheck with SARIF output
      run: |
        cppcheck --enable=all --inconclusive --sarif --output-file=cppcheck.sarif .

    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: cppcheck.sarif
